# 2.1 Data Manipulation

## Exercises

### Q1. Run the code in this section. Change the conditional statement $X == Y$ in this section to $X < Y$ or $X > Y$, and then see what kind of tensor you can get.

In [1]:
import torch

In [2]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

X < Y, X > Y

(tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

### Q2. Replace the two tensors that operate by element in the broadcasting mechanism with other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?

In [3]:
import torch

In [4]:
t1 = torch.arange(12.0).reshape(2,2,3)
t2 = torch.arange(6.0).reshape(2,3)

t1, t2

(tensor([[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.]],
 
         [[ 6.,  7.,  8.],
          [ 9., 10., 11.]]]),
 tensor([[0., 1., 2.],
         [3., 4., 5.]]))

In [5]:
t1 + t2

tensor([[[ 0.,  2.,  4.],
         [ 6.,  8., 10.]],

        [[ 6.,  8., 10.],
         [12., 14., 16.]]])

The tensor `t2` broadcasts itself into a Tensor of shape (2,2,3) with each element in dimension 0 (within the first `[]`) being equal to `t2`