# 2.2 Data Preprocessing

## Exercises

### Q1. We conducted $m = 500$ groups of experiments where each group draws $n = 10$ samples. Vary $m$ and $n$. Observe and analyze the experimental results.

In [1]:
import torch
from torch.distributions import multinomial

In [2]:
fair_probs = torch.ones([6]) / 6
print(fair_probs)

tensor([0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667])


In [3]:
m, n = 10, 500 

counts = multinomial.Multinomial(m, fair_probs).sample((n,))
total_counts = counts.sum(dim=0)
estimates = total_counts / total_counts.sum()
print(estimates)

tensor([0.1624, 0.1584, 0.1756, 0.1638, 0.1766, 0.1632])


In [4]:
m, n = 1, 500 

counts = multinomial.Multinomial(m, fair_probs).sample((n,))
total_counts = counts.sum(dim=0)
estimates = total_counts / total_counts.sum()
print(estimates)

tensor([0.1720, 0.1460, 0.1600, 0.1640, 0.1840, 0.1740])


In [5]:
m, n = 10, 5000

counts = multinomial.Multinomial(m, fair_probs).sample((n,))
total_counts = counts.sum(dim=0)
estimates = total_counts / total_counts.sum()
print(estimates)

tensor([0.1700, 0.1672, 0.1686, 0.1656, 0.1647, 0.1638])


In [6]:
m, n = 100, 50000

counts = multinomial.Multinomial(m, fair_probs).sample((n,))
total_counts = counts.sum(dim=0)
estimates = total_counts / total_counts.sum()
print(estimates)

tensor([0.1668, 0.1668, 0.1666, 0.1664, 0.1667, 0.1667])


As we increase the value of $m*n$, or the number of tosses of the die, we get closer to the true probabilities (The law of large numbers)

### Q2. Given two events with probability $P(A)$ and $P(B)$, compute upper and lower bounds on $P(A ∪ B)$ and $P(A ∩ B)$. (Hint: display the situation using a Venn Diagram.)

Bounds on $P(A ∪ B)$:
- Upper Bound: When $A$ and $B$ are disjoint, $P(A U B)$ is maximum and equal to $P(A) + P(B)$
- Lower Bound: When $A \subseteq B$ or $B \subseteq A$, $P(A U B)$ is minimum and equal to $max(P(A), P(B))$

Bounds on $P(A ∩ B)$:
- Upper Bound: When $A \subseteq B$ or $B \subseteq A$, $P(A U B)$ is maximum and equal to $min(P(A), P(B))$
- Lower Bound: When $A$ and $B$ are disjoint, $P(A U B)$ is minimum and equal to $0$

### Q3. Assume that we have a sequence of random variables, say $A$, $B$, and $C$, where $B$ only depends on $A$, and $C$ only depends on $B$, can you simplify the joint probability $P(A, B, C)$? (Hint: this is a Markov Chain.)

### Q4. In Section 2.6.2, the first test is more accurate. Why not run the first test twice rather than run both the first and second tests?

The second test is independent of the first test, hence we are able to simplify $P(D_1 = 1, D_2 = 1 | H = 0) = P(D_1 = 1 | H = 0)P(D_2 = 1 | H = 0)$. If the first test would have been used twice, the results would not have verified the former test, since the latter test would be dependent on the former.